### 예제학습 ###
모형 100개 중 최적모형1

모형 100개 중 최악모형1

In [3]:
#This problem has the following inputs: 
#1. Frequency, in Hertzs. 
#2. Angle of attack, in degrees. 
#3. Chord length, in meters. 
#4. Free-stream velocity, in meters per second. 
#5. Suction side displacement thickness, in meters. 
#6. Scaled sound pressure level, in decibels. 


import pandas as pd
df = pd.read_table("http://archive.ics.uci.edu/ml/machine-learning-databases/00291/airfoil_self_noise.dat", sep='\t',\
                   names=['Hertzs','degrees','meters1','second','meters2','decibels'])

In [18]:
df.columns[:5]

Index(['Hertzs', 'degrees', 'meters1', 'second', 'meters2'], dtype='object')

In [8]:
from sklearn import preprocessing
from sklearn import metrics
from sklearn import tree
import numpy as np

In [12]:
import sklearn
from sklearn.model_selection import train_test_split #데이터 나누는 함수
from sklearn import linear_model #선형함수
from sklearn.metrics import mean_squared_error #비교를 위한 제곱오차 계산
from sklearn.metrics import r2_score #비교를 위한 결정계수 계산용
from sklearn.datasets import load_boston #내장 데이터 로딩 함수

In [124]:
x = df[df.columns[:5]]
y = df['decibels']
pred_err = [] #반복된 모형들의 오차를 담아둘 리스트 
intercept = [] #각 시도회수만큼 계산된 모형을 담아둘 리스트
coef = [] #각 시도회수만큼 계산된 모형을 담아둘 리스트

for _ in range(100): # 위 1회 계산을 100회 반복
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
    reg = linear_model.LinearRegression()
    reg.fit(x_train,y_train)
    x_predict = reg.predict(x_test)
    pred_err.append(mean_squared_error(y_test,x_predict)) #pred_err에 저장
    intercept.append(reg.intercept_) # 상수
    coef.append(reg.coef_) #계수

In [101]:
coef

[array([ -1.26295103e-03,  -3.97381233e-01,  -3.55220335e+01,
          1.02877238e-01,  -1.57327851e+02]),
 array([ -1.25604311e-03,  -4.25610728e-01,  -3.53673006e+01,
          9.90879023e-02,  -1.34533336e+02]),
 array([ -1.30148413e-03,  -4.20375545e-01,  -3.45329547e+01,
          1.01226696e-01,  -1.48223560e+02]),
 array([ -1.26781899e-03,  -4.08975545e-01,  -3.58033609e+01,
          1.01908275e-01,  -1.43234984e+02]),
 array([ -1.24281416e-03,  -3.81126439e-01,  -3.44601927e+01,
          9.44891113e-02,  -1.57772832e+02]),
 array([ -1.26677617e-03,  -3.92767386e-01,  -3.55432304e+01,
          1.00763474e-01,  -1.61570131e+02]),
 array([ -1.26497836e-03,  -4.04574280e-01,  -3.53994207e+01,
          1.00670207e-01,  -1.52339460e+02]),
 array([ -1.23430098e-03,  -3.44990930e-01,  -3.39936832e+01,
          9.94768507e-02,  -1.62261625e+02]),
 array([ -1.32057844e-03,  -3.82871983e-01,  -3.50262428e+01,
          9.48201643e-02,  -1.73792014e+02]),
 array([ -1.26414395e-03,  -

In [125]:
min(pred_err)

17.812401026511065

In [128]:
np.array(intercept)[pred_err == min(pred_err)]

array([ 132.70460893])

In [130]:
np.array(coef)[pred_err == min(pred_err)]

array([[ -1.25235861e-03,  -3.98159992e-01,  -3.57636500e+01,
          9.94431230e-02,  -1.49197603e+02]])

In [126]:
pred_err.index(min(pred_err))

31

In [123]:
max(pred_err)

27.377091398410137

In [106]:
pred_err

[20.675545386845005,
 21.004388017580361,
 22.395763444487937,
 23.237397100189071,
 24.502490900012205,
 21.072656582628923,
 25.946301996232144,
 26.503426074312095,
 25.199777503496872,
 25.035026462519081,
 19.726375618784168,
 20.917215226581359,
 25.727080333085304,
 20.914662947006033,
 24.056181120544377,
 22.915284950242537,
 23.05794336867682,
 22.27769773382963,
 16.359856263417921,
 24.234126237547823,
 20.457414655047746,
 24.179526817457205,
 23.242542407290419,
 21.398862744040819,
 20.375804188686857,
 26.554706083791817,
 24.719872847597724,
 25.361571473081671,
 20.955932248695955,
 20.875411653700098,
 24.245103384600871,
 22.498946605662038,
 23.721658559583616,
 23.396355316709368,
 19.543073798472165,
 23.652907178879993,
 21.261751849369464,
 22.092500344720364,
 24.219420520762871,
 22.662641867728425,
 23.164606928096795,
 23.472474100148201,
 24.389470906585409,
 22.110287851691243,
 22.154338450982017,
 19.992934160452144,
 23.942430254697243,
 23.54897127315